// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aunqyhcyisiffmreclep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bnF5aGN5aXNpZmZtcmVjbGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjA0NDUsImV4cCI6MjA2NDYzNjQ0NX0.EXxfsBtJE5qHN2BFq8RgbUuupIBpd5Z_5sQrHQZkUAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);